apiVersion: v1
kind: Service
metadata:
  name: mi-api-service
  namespace: mi-api-ns
spec:
  selector:
    app: mi-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort